// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const scrollDrivenLogo: string;
export const pcDocsHeaderLogoScale: string;
export const scrollDrivenNav: string;
export const pcDocsHeaderNavShift: string;
