name: Build

on:
  push:
    branches: ['master', 'docs-staging']
    paths-ignore:
      - '.github/**'
  workflow_dispatch:
    inputs:
      hash:
        description: 'Docs Staging Hash'
        type: string
        default: master
        required: true

concurrency: ci-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build website
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install deps
        run: yarn

      - name: Update submodule
        run: |
          git submodule update --remote

      - name: Restore gatsby cache
        uses: actions/cache@v3
        id: gatsby-cache
        with:
          path: |
            .cache
            public
          key: ${{ runner.os }}-gatsby-cache-docs-staging-${{ inputs.hash }}
          restore-keys: |
            ${{ runner.os }}-gatsby-cache-docs-staging-

      - name: Print cache key
        run: |
          echo ${{ runner.os }}-gatsby-cache-docs-staging-${{ inputs.hash }}

      - name: Build website
        env:
          CI: true
          GATSBY_ALGOLIA_APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
          GATSBY_ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
        run: |
          yarn build --verbose

      # - name: Deploy to LA1
      #   run: |
      #     rsync -avz --delete public/ "${{ secrets.SSH_USER }}@${{ secrets.LA_1_HOST }}:${{ secrets.DEPLOY_PATH }}"

      # - name: Deploy to LA2
      #   run: |
      #     rsync -avz --delete public/ "${{ secrets.SSH_USER }}@${{ secrets.LA_2_HOST }}:${{ secrets.DEPLOY_PATH }}"

      # - name: Deploy to BJ1
      #   run: |
      #     rsync -avz --delete -e 'ssh -p ${{ secrets.BJ_1_PROXY_PORT }} -o StrictHostKeyChecking=no' public/ "${{ secrets.SSH_USER }}@${{ secrets.BJ_PROXY_HOST }}:${{ secrets.DEPLOY_PATH }}"

      # - name: Deploy to BJ2
      #   run: |
      #     rsync -avz --delete -e 'ssh -p ${{ secrets.BJ_2_PROXY_PORT }} -o StrictHostKeyChecking=no' public/ "${{ secrets.SSH_USER }}@${{ secrets.BJ_PROXY_HOST }}:${{ secrets.DEPLOY_PATH }}"
