name: Upload test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Upload to COS
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "master"

      - name: AWS CLI Config Init
        run: |
          mkdir -p ~/.aws
          touch ~/.aws/config
          echo "[default]
          s3 =
              addressing_style = virtual " > ~/.aws/config
          touch ~/.aws/credentials
          echo "[default]
          aws_access_key_id=${{ secrets.TENCENTCLOUD_SECRET_ID }}
          aws_secret_access_key=${{ secrets.TENCENTCLOUD_SECRET_KEY }}" > ~/.aws/credentials

      - name: Upload test file
        run: |
          aws s3 sync README.md s3://${{ secrets.TENCENTCLOUD_BUCKET_ID }}/README.md \
            --no-progress \
            --follow-symlinks \
            --size-only \
            --delete \
            --endpoint-url https://cos.na-ashburn.myqcloud.com

      - name: AWS CLI Config Clear
        run: cat /dev/null > ~/.aws/credentials
