name: Upload test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Upload to COS
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "master"

      - name: Install coscli
        run: |
          wget https://cosbrowser.cloud.tencent.com/software/coscli/coscli-linux-amd64
          mv coscli-linux-amd64 coscli
          chmod 755 coscli
          ls | grep coscli

      - name: Upload test file
        run: |
          ls | grep coscli
          coscli cp README.md s3://${{ secrets.TENCENTCLOUD_BUCKET_ID }}/README.md \
            --init-skip \
            --recursive \
            --secret-id=${{ secrets.TENCENTCLOUD_SECRET_ID }} \
            --secret-key=${{ secrets.TENCENTCLOUD_SECRET_KEY }} \
            --endpoint-url https://cos.na-ashburn.myqcloud.com
