name: Upload test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Upload to COS
    env:
      RCLONE_CONN_STRING: ":s3,endpoint=cos.ap-beijing.myqcloud.com,access_key_id=${{ secrets.TENCENTCLOUD_SECRET_ID }},secret_access_key=${{ secrets.TENCENTCLOUD_SECRET_KEY }},force_path_style=false"
      TENCENTCLOUD_BUCKET_ID: ${{ secrets.TENCENTCLOUD_BUCKET_ID }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "master"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TENCENTCLOUD_SECRET_ID }}
          aws-secret-access-key: ${{ secrets.TENCENTCLOUD_SECRET_KEY }}

      - name: Upload test file
        env:
          TENCENTCLOUD_BUCKET_ID: ${{ secrets.TENCENTCLOUD_BUCKET_ID }}
        run: |
          aws s3 sync README.md s3://${TENCENTCLOUD_BUCKET_ID}/README.md \
            --no-progress \
            --follow-symlinks \
            --size-only \
            --delete \
            --endpoint-url https://cos.na-ashburn.myqcloud.com
