name: Upload test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Upload to COS
    env:
      RCLONE_CONN_STRING: ":s3,endpoint=cos.ap-beijing.myqcloud.com,access_key_id=${{ secrets.TENCENTCLOUD_SECRET_ID }},secret_access_key=${{ secrets.TENCENTCLOUD_SECRET_KEY }},force_path_style=false"
      TENCENTCLOUD_BUCKET_ID: ${{ secrets.TENCENTCLOUD_BUCKET_ID }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "master"

      - name: Install rclone
        run: |
          curl -O https://downloads.rclone.org/rclone-current-linux-amd64.zip
          unzip rclone-current-linux-amd64.zip
          mv rclone-*-linux-amd64/rclone ./

      - name: Upload test file
        run: ./rclone copyto README.md "${RCLONE_CONN_STRING}:${TENCENTCLOUD_BUCKET_ID}/README.md"
